name: Auto Version on Merge to Master

on:
  pull_request_target:
    types: [closed]
    branches: [ master, main ]

jobs:
  bump:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout base (master)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Determine release type (labels or conventional commits)
        id: rel
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          TYPE="minor"
          # 1) Prefer explicit labels
          echo '${{ toJson(github.event.pull_request.labels) }}' | jq -r '.[].name' | while read -r name; do
            case "$name" in
              release:major) TYPE=major ;;
              release:minor) TYPE=minor ;;
              release:patch) TYPE=patch ;;
            esac
          done
          # 2) If still default, infer from PR title and commit messages (Conventional Commits)
          if [ -n "$TYPE" ]; then
            TITLE='${{ github.event.pull_request.title }}'
            TITLE_LC=$(echo "$TITLE" | tr '[:upper:]' '[:lower:]')
            if echo "$TITLE" | grep -qE 'BREAKING CHANGE|!'; then TYPE="major"; fi
            if echo "$TITLE_LC" | grep -q '^feat'; then TYPE="minor"; fi
            # Fetch commits and evaluate
            COMMITS=$(curl -sSL -H "Authorization: Bearer $GH_TOKEN" -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/commits")
            MSGS=$(echo "$COMMITS" | jq -r '.[].commit.message')
            if echo "$MSGS" | grep -qE 'BREAKING CHANGE|!'; then TYPE="major"; fi
            # Keep minor by default when no clear signal; escalate to major if breaking
          fi
          echo "Selected bump type: $TYPE"
          echo "type=$TYPE" >> $GITHUB_OUTPUT

      - name: Config git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Bump version and tag
        run: |
          set -e
          TYPE=${{ steps.rel.outputs.type }}
          # 1) Bump without creating a git tag yet
          npm version "$TYPE" --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")
          echo "Initial bump target: v$VERSION"

          # 2) If tag already exists, auto-increment patch until a free tag is found (max 5 tries)
          i=0
          while git rev-parse -q --verify "refs/tags/v$VERSION" >/dev/null; do
            echo "Tag v$VERSION already exists. Bumping patch..."
            npm version patch --no-git-tag-version
            VERSION=$(node -p "require('./package.json').version")
            i=$((i+1))
            if [ $i -ge 5 ]; then
              echo "Reached max attempts trying to find a free version tag." >&2
              exit 1
            fi
          done

          # 3) Commit, tag and push
          git add package.json package-lock.json 2>/dev/null || true
          git commit -m "chore(release): v$VERSION"
          git tag -a "v$VERSION" -m "chore(release): v$VERSION"
          git push
          git push origin "v$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
