name: OpenAPI Check

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
      - name: Run OpenAPI check (bundle + lint + report)
        run: |
          pnpm run check -- example/openapi.yaml --docs
        env:
          SCHEMA_LINT: '1'
          CI: '1'
