name: CI

permissions:
  contents: read
  security-events: write

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  test:
    name: Test, build and smoke grade
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            ~/.cache/pnpm
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Enable Corepack and install deps
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Run soft grade (example spec)
        # Use soft mode in CI to avoid failing the job due to grading policy.
        run: |
          GRADE_SOFT=1 pnpm run check -- example/openapi.yaml || true

      - name: Generate static report (example)
        # Generate a static report under dist/ so it can be archived as an artifact
        run: |
          pnpm run report:static -- example/openapi.yaml

      - name: Upload report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: grade-report-dist
          path: dist

  codeql:
    name: CodeQL Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis (no upload)
        uses: github/codeql-action/analyze@v2
        with:
          upload: false

      - name: Upload CodeQL SARIF (skip for forked PRs)
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
        uses: github/codeql-action/upload-sarif@v2
