name: Debug Grade Script

on:
  workflow_dispatch:

jobs:
  debug-grade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack and prepare pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Tool diagnostics (safe)
        run: |
          node -e "console.log('Node:', process.version)"
          pnpm -v || echo 'pnpm not available'
          pnpm exec -- spectral --version || echo 'spectral not available via pnpm exec'
          # redocly is optional and may not be published/installed; do not fail here
          pnpm exec -- redocly --version 2>/dev/null || echo 'redocly not available via pnpm exec (optional)'
          echo "node_modules/.bin contents:" && ls -la node_modules/.bin || true
          echo "Top-level installed packages:" && pnpm list --depth 0 || true

      - name: Run check (debug env, schema lint OFF by default)
        env:
          DEBUG_CLI_ARGS: '1'
          SCHEMA_LINT: '0'
        run: pnpm run -s check -- -- example/openapi.yaml
