name: Docker Smoke Test (GHCR)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag to pull from GHCR'
        required: false
        default: 'latest'

jobs:
  smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    env:
      REGISTRY: ghcr.io
      IMAGE: ghcr.io/${{ github.repository }}:${{ inputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show image reference
        run: echo "Image: $IMAGE"

      - name: Login to GHCR (optional)
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        run: docker pull "$IMAGE"

      - name: Validate example using container
        run: |
          docker run --rm -v "${{ github.workspace }}:/work" "$IMAGE" \
            npm run validate -- /work/example/openapi.yaml

      - name: Grade example using container
        run: |
          docker run --rm -e SCHEMA_LINT=1 -v "${{ github.workspace }}:/work" "$IMAGE" \
            npm run grade -- /work/example/openapi.yaml

      - name: Check grade report exists
        run: |
          test -f dist/grade-report.json
          echo "Grade report present."
          head -n 50 dist/grade-report.json || true

      - name: Upload smoke artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docker-smoke-out
          path: |
            dist/grade-report.json
            dist/bundled-*

