name: API Lint

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install deps
        run: pnpm install

      - name: Validate example spec
        run: pnpm run validate -- example/openapi.yaml

      - name: Grade example spec (with schema lint)
        run: SCHEMA_LINT=1 pnpm run grade -- example/openapi.yaml

