name: API Lint

# This workflow is triggered after the 'Run Tests' workflow finishes successfully.
# We use workflow_run so linting runs only when tests passed. This prevents
# running expensive API lint/grade before basic tests complete.
on:
  workflow_run:
    workflows: ["Run Tests"]
    types: [completed]
  workflow_dispatch:

jobs:
  lint:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '9'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Redocly diagnostics
        run: |
          echo "Node: $(node -v)"
          echo "pnpm: $(pnpm -v)"
          echo "Check redocly binary (pnpm exec):"
          pnpm exec -- redocly --version || echo 'redocly not available via pnpm exec'
          echo "node_modules/.bin contents:" && ls -la node_modules/.bin || true
          echo "Top-level installed packages:" && pnpm list --depth 0 || true

      - name: Repo diagnostics
        run: |
          echo "Current dir: $(pwd)"
          echo "Git branch: $(git rev-parse --abbrev-ref HEAD || echo 'no-branch')"
          echo "Git HEAD: $(git rev-parse HEAD || echo 'no-commit')"
          echo "Listing root files:" && ls -la || true
          echo "Listing scripts/:" && ls -la scripts || true
          echo "Head of scripts/grade.mjs:" && sed -n '1,80p' scripts/grade.mjs || true
          echo "Does scripts/bundle.mjs exist?" && [ -f scripts/bundle.mjs ] && echo 'bundle.mjs present' || echo 'bundle.mjs missing'

      - name: Validate example spec
        run: |
          echo 'Before validate: dist contents:' && ls -la dist || true
          pnpm run check -- example/openapi.yaml --no-bundle
          echo 'After validate: dist contents:' && ls -la dist || true

      - name: Grade example spec (with schema lint)
        run: SCHEMA_LINT=1 pnpm run check -- example/openapi.yaml

