name: API Lint

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install deps
        run: npm ci

      - name: Validate example spec
        run: npm run validate -- example/openapi.yaml

      - name: Grade example spec (with schema lint)
        run: SCHEMA_LINT=1 npm run grade -- example/openapi.yaml

