name: Reusable • OpenAPI Validate

on:
  workflow_call:
    inputs:
      spec_path:
        type: string
        required: true
        description: Path to OpenAPI (in caller repo)
      tools_ref:
        type: string
        required: false
        default: 'develop'
      schema_lint:
        type: string
        required: false
        default: '0'
        description: Enable Redocly schema lint (1/0)
      tools_repo:
        type: string
        required: false
        default: 'ramongranda/openapi-anyenv-suite'
        description: Tools repository to checkout

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout caller repo
        uses: actions/checkout@v4

      - name: Checkout tools repo (or use local workspace if same repo)
        if: ${{ inputs.tools_repo != github.repository }}
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.tools_repo }}
          path: tools
          ref: ${{ inputs.tools_ref }}


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '9'
      - name: Install tools
        working-directory: ${{ inputs.tools_repo == github.repository && github.workspace || 'tools' }}
        run: pnpm install --frozen-lockfile

      - name: Validate (canonical)
        working-directory: ${{ inputs.tools_repo == github.repository && github.workspace || 'tools' }}
        env:
          SCHEMA_LINT: ${{ inputs.schema_lint }}
        run: pnpm run check -- ../${{ inputs.spec_path }} --no-bundle

      - name: Upload bundle
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: openapi-bundle
          path: tools/dist/**
