name: Publish to npm

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  publish:
    name: Publish package to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.10.0'

      - name: Ensure pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@10.19.0 --activate

      - name: Configure npm auth
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ -z "$NPM_TOKEN" ]; then echo "ERROR: NPM_TOKEN secret is not set"; exit 1; fi
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

      - name: Install dependencies (pnpm)
        run: |
          pnpm install --frozen-lockfile

      - name: Ensure conventional commits parser is available
        run: |
          corepack enable || true
          corepack prepare pnpm@10.19.0 --activate || true
          pnpm add -D conventional-changelog-conventionalcommits@^4.3.0

      - name: Read package version
        id: pkg
        run: |
          # Use node -e to avoid nested-quote parsing issues
          VERSION=$(node -e "console.log(require('./package.json').version)")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # semantic-release runs on main and will create tags/releases itself

      - name: Run semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          corepack enable || true
          pnpm install --frozen-lockfile
          npx semantic-release
