name: Pull Request Dry Run

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  semantic-release-dry-run:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Semantic Release Dry Run
        id: semrel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eo pipefail
          pnpm dlx semantic-release --dry-run --debug | tee semrel.log

          # Extrae la versión del log (formato estándar y alternativo)
          VERSION=$(grep -oiE "the next release version is[[:space:]]+v?[0-9]+\.[0-9]+\.[0-9]+([.-][0-9A-Za-z]+)*" semrel.log \
            | tail -n1 | sed -E 's/.*is[[:space:]]+v?//I')

          if [ -z "$VERSION" ]; then
            VERSION=$(grep -oE "nextRelease[^}]*version['\"]?[[:space:]]*:[[:space:]]*['\"][0-9]+\.[0-9]+\.[0-9]+([.-][0-9A-Za-z]+)*" semrel.log \
              | tail -n1 | sed -E "s/.*version['\"]?[[:space:]]*:[[:space:]]*['\"]//; s/['\"]$//")
          fi

          echo "version=${VERSION:-unknown}" >> "$GITHUB_OUTPUT"

          # Adjunta últimas 200 líneas del log al output (multilínea)
          echo "log<<EOF" >> "$GITHUB_OUTPUT"
          tail -n 200 semrel.log >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Comment on Pull Request
        if: ${{ success() && github.event.pull_request.head.repo.full_name == github.repository }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### semantic-release dry-run
            **Proposed version:** ${{ steps.semrel.outputs.version }}

            <details><summary>Dry-run output (last 200 lines)</summary>

            ```
            ${{ steps.semrel.outputs.log }}
            ```

            </details>
