name: Tag From package.json Version

on:
  push:
    branches: [ master, main ]

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect version bump
        id: ver
        run: |
          set -e
          BASE=$(git rev-parse HEAD^ || echo "")
          if [ -z "$BASE" ]; then echo "bumped=true" >> $GITHUB_OUTPUT; exit 0; fi
          git show "$BASE:package.json" > /tmp/base.package.json || echo '{}' > /tmp/base.package.json
          CURR=$(node -p "require('./package.json').version")
          PREV=$(node -e "console.log(require('/tmp/base.package.json').version||'')")
          echo "prev=$PREV" >> $GITHUB_OUTPUT
          echo "curr=$CURR" >> $GITHUB_OUTPUT
          if [ "$CURR" != "$PREV" ] && [ -n "$CURR" ]; then
            echo "bumped=true" >> $GITHUB_OUTPUT
          else
            echo "bumped=false" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tag
        if: ${{ steps.ver.outputs.bumped == 'true' }}
        env:
          VERSION: ${{ steps.ver.outputs.curr }}
        run: |
          set -e
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          TAG="v${VERSION}"
          if git rev-parse -q --verify "refs/tags/$TAG" >/dev/null; then
            echo "Tag $TAG already exists; skipping"
            exit 0
          fi
          git tag "$TAG"
          git push origin "$TAG"

